package com.ismail.hiberPro01.hibernate.pojo;
// Generated Jun 14, 2020 2:02:56 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emps generated by hbm2java
 */
@Entity
@Table(name = "emps", catalog = "emp")
public class Emps implements java.io.Serializable {

	private int idemps;
	private Address address;
	private String empName;
	private long salary;

	public Emps() {
	}

	public Emps(int idemps, Address address, String empName, long salary) {
		this.idemps = idemps;
		this.address = address;
		this.empName = empName;
		this.salary = salary;
	}

	@Id

	@Column(name = "idemps", unique = true, nullable = false)
	public int getIdemps() {
		return this.idemps;
	}

	public void setIdemps(int idemps) {
		this.idemps = idemps;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "emp_name", nullable = false, length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "salary", nullable = false, precision = 10, scale = 0)
	public long getSalary() {
		return this.salary;
	}

	public void setSalary(long salary) {
		this.salary = salary;
	}

}
